# Site settings
title: LISEM
email: b.vandenbout@utwente.nl
description: >
  LISEM website, open-source spatial modelling software download and tutorials.
lang: en-US

baseurl: "/LISEM" # the subpath of your site, e.g. /blog/
url: "https://bastianvandenbout.github.io" # the base hostname & protocol for your site
git_address: https://github.com/bastianvandenbout/LISEM
git_edit_address: https://github.com/bastianvandenbout/LISEM

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - third_party/
  - scripts/
  - resources/
  - lisem/
  - cmakeFindModules/
  - CMakeLists.txt
  - lisem.ico
  - lisem.rc
  - NSIS.template.in
  - pylisem_script/
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    search: true
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
      
      
- scope:
    path: _pages
    type: pages
  values:
    search: true
    layout: docs2
    sectionid: pages
    seo:
      type: "WebPage"

- scope:
    path: _showcases
    type: showcases
  values:
    search: true
    layout: showcase
    sectionid: showcases
    seo:
      type: "WebPage"
      
      
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  pages:
    permalink: /:collection/:path/
    output: true
  showcases:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
