# ==============================================================================
# Get all the external libraries
# ==============================================================================


set(QT_USE_QTOPENGL TRUE)





if(LISEM_USE_EXTERNALDIR)


SET(EXTERNAL_DIR "" CACHE PATH "EXTERNAL_DIR")


# ==============================================================================
# USING EXTERNAL DIR
# ==============================================================================


IF(EXISTS ${EXTERNAL_DIR})

SET(EXTERNAL_INCLUDE_DIR "${EXTERNAL_DIR}/include" )
SET(EXTERNAL_LIB_DIR "${EXTERNAL_DIR}/lib" )

ELSE()
#this is the main external libraries collection
#here, the cmake configuration tries to find all other dependencies
SET(EXTERNAL_INCLUDE_DIR "")
SET(EXTERNAL_LIB_DIR "")
SET(LISEM_EXTERNAL_LIBS "")

MESSAGE("Did not Find External Dir")
message(FATAL_ERROR "Specify the folder containing external libraries using EXTERNAL_DIR" )
ENDIF()

#assume we have OpenMP
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${OpenMP_SHARED_LINKER_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")

set(Qt5Core_DIR "/mingw64/lib/cmake/Qt5Core")
set(Qt5Network_DIR "/mingw64/lib/cmake/Qt5Network")
set(Qt5OpenGL_DIR "/mingw64/lib/cmake/Qt5OpenGL")
set(Qt5Widgets_DIR "/mingw64/lib/cmake/Qt5Widgets")
set(Qt5Multimedia_DIR "/mingw64/lib/cmake/Qt5Multimedia")
set(Qt5Multimedia_DIR "/mingw64/lib/cmake/Qt5Xml")

find_package(OpenGL REQUIRED)
find_package(Qt5Core CONFIG REQUIRED)
find_package(Qt5Network CONFIG REQUIRED)
find_package(Qt5Widgets CONFIG REQUIRED)
find_package(Qt5OpenGL CONFIG REQUIRED)
find_package(Qt5Multimedia CONFIG REQUIRED)
find_package(Qt5Xml CONFIG REQUIRED)

set_target_properties(Qt5::Core PROPERTIES MAP_IMPORTED_CONFIG_COVERAGE "RELEASE")

add_definitions(${Qt5Widgets_DEFINITIONS})
add_definitions(${Qt5Core_DEFINITIONS})
add_definitions(${Qt5Gui_DEFINITIONS})
add_definitions(${Qt5Network_DEFINITIONS})
add_definitions(${Qt5Xml_DEFINITIONS})

FIND_PACKAGE(MPI REQUIRED)
ADD_DEFINITIONS(${MPI_C_COMPILE_FLAGS})
ADD_DEFINITIONS(${MPI_CXX_COMPILE_FLAGS})
INCLUDE_DIRECTORIES(${MPI_C_INCLUDE_PATH})
INCLUDE_DIRECTORIES(${MPI_CXX_INCLUDE_PATH})



INCLUDE(FortranCInterface)
FortranCInterface_HEADER(FC.h MACRO_NAMESPACE "FC_")
ADD_DEFINITIONS(-DCMAKE_FC_FUNC="1")


    
    
    
    
    
    
    


LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${EXTERNAL_INCLUDE_DIR})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS "${EXTERNAL_DIR}/include_ITK" )
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS "${EXTERNAL_DIR}/include_OTB" )
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${GLFW_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OpenCL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Network_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Widgets_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Core_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5OpenGL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Gui_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Multimedia_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Xml_INCLUDE_DIRS})

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libnodes.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libarmadillo.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libmlpack.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libglfw3.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/opencl.lib")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libangelscript.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libgdal-28.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libfreetype.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpcraster_raster_format.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/msys-mlpack-3.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/avcodec-58.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/avformat-58.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/avutil-56.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/avdevice-58.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/avfilter-7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/swscale-5.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libmuparser.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libChronoEngine.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libassimp.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpdal.dll.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpdal_util.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpdalcpp.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpdal_kazhdan.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblibpdal_plugin_kernel_fauxplugin.dll.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKBiasCorrection-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKCommon-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKDICOMParser-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkdouble-conversion-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKFFT-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKgiftiio-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOBioRad-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOBMP-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOBruker-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOCSV-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOGDCM-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOGE-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOGIPL-5.0.dll" )
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOHDF5-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOImageBase-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOIPL-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOJPEG2000-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOJPEG-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOLSM-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshBase-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshBYU-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshFreeSurfer-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshGifti-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshOBJ-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshOFF-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeshVTK-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMeta-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMINC-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOMRC-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIONIFTI-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIONRRD-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOPNG-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOSiemens-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOSpatialObjects-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOStimulate-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOTIFF-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOTransformBase-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOTransformHDF5-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOTransformInsightLegacy-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOTransformMatlab-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOVTK-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKIOXML-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKKLMRegionGrowing-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKLabelMap-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitklbfgs-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKMesh-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKMetaIO-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitknetlib-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkNetlibSlatec-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKniftiio-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKNrrdIO-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkopenjpeg-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKOptimizers-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKOptimizersv4-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKPath-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKPolynomials-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKQuadEdgeMesh-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKSpatialObjects-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKStatistics-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitksys-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKTestKernel-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitktestlib-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKTransform-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKTransformFactory-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkv3p_netlib-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkvcl-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVideoBridgeOpenCV-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVideoCore-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVideoIO-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkvnl-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libitkvnl_algo-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVNLInstantiation-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVTK-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKVtkGlue-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKWatersheds-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libITKznz-5.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libotb6S-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libotb6S-7.0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBApplicationEngine-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBCarto-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBCommon-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBCurlAdapters-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBExtendedFilename-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBFuzzy-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBGdalAdapters-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBImageBase-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBImageIO-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBImageManipulation-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIOBSQ-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIOGDAL-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIOLUM-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIOMSTAR-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIOONERA-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBIORAD-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBLearningBase-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBMathParser-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBMetadata-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBOpticalCalibration-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBOSSIMAdapters-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libotbossimplugins-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBPolarimetry-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBProjection-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBSampling-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libotbsiftfast-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBSimulation-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBStatistics-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBStreaming-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBSupervised-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBTestKernel-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBVectorDataBase-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBVectorDataIO-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libOTBWavelet-6.7.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/boost_wserialization-vc140-mt-x64-1_69.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/boost_serialization-vc140-mt-x64-1_69.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libboost_wserialization-mt.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libboost_serialization-mt.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/shark.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/svm.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libblas.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libcblas.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblapack.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblapacke.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libtmglib.dll")


LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libglog.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_cxsparse.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_sfm.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_easyexif.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_exif.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_fast.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_features.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_geometry.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_kvld.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_lemon.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_lInftyComputerVision.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_matching_image_collection.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_matching.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_multiview.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_multiview_test_data.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_numeric.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_robust_estimation.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_stlplus.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_system.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_image.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_linearProgramming.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libvlsift.a")


LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenMVG_ceres.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblib_OsiClpSolver.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblib_CoinUtils.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblib_clp.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/liblib_Osi.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libceres.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopencv_dnn_superres451.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopencv_dnn451.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopencv_world451.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libjpeg-8.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libjpegxr.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libtiff-5.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libpng16-16.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libfftw3-3.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libfftw3f-3.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libfftw3l-3.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libgmp-10.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libgmpxx-4.dll")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/zlib1.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libbz2.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libboost_iostreams-mt.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libimagehlp.a")

LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libg3m.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libarchive-13.dll")
#LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libMVS.dll.a")
#LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libMVS.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libnetcdf.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libhdf5_cpp-0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libhdf5_hl_cpp-0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libhdf5-0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libhdf5_hl-0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libhdf5_tools-0.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libgsl.a")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libbox2d.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libopenal-1.dll")
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Widgets_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Core_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Network_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5OpenGL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Multimedia_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Xml_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MPI_C_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MPI_CXX_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OPENGL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS "libstdc++.a")


#LIST(APPEND LISEM_EXTERNAL_LIBS "${EXTERNAL_LIB_DIR}/libmsvcr120.a")




# ==============================================================================
# USING NORMAL FIND
# ==============================================================================

else()



FIND_PACKAGE(MPI REQUIRED)
ADD_DEFINITIONS(${MPI_C_COMPILE_FLAGS})
ADD_DEFINITIONS(${MPI_CXX_COMPILE_FLAGS})
INCLUDE_DIRECTORIES(${MPI_C_INCLUDE_PATH})
INCLUDE_DIRECTORIES(${MPI_CXX_INCLUDE_PATH})



INCLUDE(FortranCInterface)
FortranCInterface_HEADER(FC.h MACRO_NAMESPACE "FC_")
ADD_DEFINITIONS(-DCMAKE_FC_FUNC="1")



message(STATUS "Checking OpenMP")
find_package(OpenMP)
IF(OPENMP_FOUND)
    message("Found OpenMP!")
    # add flags for OpenMP
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${OpenMP_SHARED_LINKER_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
ELSE()
    message("Missed OpenMP! x_x")
ENDIF()

set(ITK_NO_IO_FACTORY_REGISTER_MANAGER ON)

find_package(OpenGL REQUIRED)
find_package(Qt5Gui CONFIG REQUIRED)
find_package(Qt5Core CONFIG REQUIRED)
find_package(Qt5Network CONFIG REQUIRED)
find_package(Qt5Widgets CONFIG REQUIRED)
find_package(Qt5OpenGL CONFIG REQUIRED)
find_package(Qt5Multimedia CONFIG REQUIRED)

set_target_properties(Qt5::Core PROPERTIES MAP_IMPORTED_CONFIG_COVERAGE "RELEASE")
add_definitions(${Qt5Widgets_DEFINITIONS})
add_definitions(${Qt5Core_DEFINITIONS})
add_definitions(${Qt5Gui_DEFINITIONS})
add_definitions(${Qt5Network_DEFINITIONS})


find_package(GDAL 2.0 REQUIRED)
find_package(ITK 4.0 REQUIRED)
include(${ITK_USE_FILE})
find_package(OTB 7.0 COMPONENTS OTB6S OTBBoost OTBBoostAdapters OTBGDAL OTBITK OTBCommon OTBGdalAdapters OTBOpenThreads OTBOssim OTBGeoTIFF OTBOssimPlugins OTBOSSIMAdapters OTBObjectList OTBMetadata OTBImageBase OTBFunctor OTBAnomalyDetection OTBTinyXML OTBVectorDataBase OTBIOGDAL OTBExtendedFilename OTBIOBSQ OTBIOLUM OTBIOMSTAR OTBIOONERA OTBIORAD OTBImageList OTBStreaming OTBImageIO OTBInterpolation OTBTransform OTBImageManipulation OTBPath OTBVectorDataManipulation OTBProjection OTBVectorDataIO OTBApplicationEngine OTBMoments OTBLabelMap OTBConversion OTBMosaic OTBStatistics OTBChangeDetection OTBAppChangeDetection OTBPointSet OTBSiftFast OTBDescriptors OTBAppDescriptors OTBDimensionalityReduction OTBLearningBase OTBSOM OTBDimensionalityReductionLearning OTBIOXML OTBAppDimensionalityReduction OTBWavelet OTBAppDomainTransform OTBEdge OTBAppEdge OTBContrast OTBSmoothing OTBAppFiltering OTBEndmembersExtraction OTBUnmixing OTBAppHyperspectral OTBCurlAdapters OTBCarto OTBColorMap OTBAppImageUtils OTBFuzzy OTBIndices OTBAppIndices OTBAppMoments OTBMorphologicalProfiles OTBAppMorphology OTBOpticalCalibration OTBAppOpticalCalibration OTBSARCalibration OTBAppSARCalibration OTBPolarimetry OTBAppSARDecompositions OTBAppSARPolarMatrixConvert OTBAppSARPolarSynth OTBImageNoise OTBAppSARUtils OTBAppTest OTBTextures OTBAppTextures OTBAppVectorDataTranslation OTBAppVectorUtils OTBCloudDetection OTBCommandLine OTBComplexImage OTBConvolution OTBCorner OTBDEM OTBDensity OTBStereo OTBDisparityMap OTBLabelling OTBLandSatClassifier OTBMajorityVoting OTBMarkov OTBMetrics OTBOGRProcessing OTBOpenCV OTBPanSharpening OTBSWIGWrapper OTBSampling OTBSimulation OTBUnsupervised OTBSupervised OTBTestKernel OTBTimeSeries OTBWatersheds REQUIRED)
INCLUDE(${OTB_USE_FILE})

find_package(Boost 1.66.0 COMPONENTS filesystem serialization system program_options iostreams REQUIRED)

set(Boost_USE_STATIC_LIBS        ON)
set(Boost_USE_DEBUG_LIBS        OFF)
set(Boost_USE_RELEASE_LIBS       ON)
set(Boost_USE_MULTITHREADED      ON)
set(Boost_USE_STATIC_RUNTIME    OFF)

find_package(assimp REQUIRED)
find_package(PDAL REQUIRED)
find_package(LibArchive REQUIRED)
find_package(Freetype REQUIRED)
find_package(FFMPEG COMPONENTS AVCODEC AVDEVICE AVFORMAT AVFILTER AVUTIL SWSCALE REQUIRED)
find_package(GLFW REQUIRED)
find_package(Chrono REQUIRED)
find_package(OpenCV REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(OpenMVS REQUIRED)
find_package(OpenMVG REQUIRED)
find_package(Ceres REQUIRED)
find_package(Armadillo REQUIRED)
find_package(CGAL REQUIRED)
find_package(Superlu REQUIRED)
find_package(NodeEditor REQUIRED)
find_package(MLPACK REQUIRED)
find_package(Angelscript REQUIRED)
find_package(OpenCL REQUIRED)
find_package(MuParser REQUIRED)
find_package(MuParserX REQUIRED)

LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Gui_IBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Widgets_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Core_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Network_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5OpenGL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Qt5Multimedia_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MPI_C_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MPI_CXX_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OPENGL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${FFMPEG_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${GDAL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${LibArchive_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${ASSIMP_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${SWSCALE_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${FREETYPE_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${GLFW_LIBRARY})
LIST(APPEND LISEM_EXTERNAL_LIBS ${Boost_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${CHRONO_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OPENCV_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OpenMVS_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OpenMVG_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS 
OpenMVG::openMVG_camera
OpenMVG::openMVG_exif
OpenMVG::openMVG_features
OpenMVG::openMVG_geodesy
OpenMVG::openMVG_geometry
OpenMVG::openMVG_graph
OpenMVG::openMVG_image
OpenMVG::openMVG_linearProgramming
OpenMVG::openMVG_matching
OpenMVG::openMVG_matching_image_collection
OpenMVG::openMVG_multiview
OpenMVG::openMVG_numeric
OpenMVG::openMVG_robust_estimation
OpenMVG::openMVG_sfm
OpenMVG::openMVG_system
OpenMVG::vlsift)
LIST(APPEND LISEM_EXTERNAL_LIBS ${Ceres_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${ARMADILLO_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${CGAL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${SUPERLU_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${NodeEditor_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${PDAL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OpenCL_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${ITK_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${OTB_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MLPACK_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS Angelscript::angelscript)
LIST(APPEND LISEM_EXTERNAL_LIBS ${MUPARSER_LIBRARIES})
LIST(APPEND LISEM_EXTERNAL_LIBS ${MUPARSERX_LIBRARIES})

LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${GLFW_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OpenCL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Gui_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Network_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Widgets_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Core_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5OpenGL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Gui_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Qt5Multimedia_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${GDAL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${LibArchive_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${ASSIMP_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${FREETYPE_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OPENCL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${GLFW_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${BOOST_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${CHRONO_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OPENCV_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${EIGEN_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OpenMVS_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${OTB_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${CERES_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${ARMADILLO_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${CGAL_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${SUPERLU_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${NODEEDITOR_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${MLPACK_INCLUDE_DIRS})
LIST(APPEND LISEM_EXTERNAL_INCLUDE_DIRS ${Angelscript_INCLUDE_DIRS})
if(GLFW_FOUND)

message("glfw")
#message(${MuParser_LIBRARIES})
else()
message("OpenCL not found!")
endif()

endif()


ADD_DEFINITIONS(-D_USE_BOOST)
ADD_DEFINITIONS(-D_USE_EIGEN)
ADD_DEFINITIONS(-D_USE_PNG)
ADD_DEFINITIONS(-D_USE_JPG)
ADD_DEFINITIONS(-D_USE_TIFF)

